server:
  port: 8080
  
spring:  application:    name: "hotel-service-gateway"
    
############Comment this if discovery from eureka not needed############
#  cloud:#    gateway:#      discovery:#        locator:#          enabled: true
#          lower-case-service-id: true
#      default-filters:#      - name: 
      #############################################
    
eureka:  client:    fetch-registry: true
    register-with-eureka: true
  instance:    hostname: localhost
    prefer-ip-address: true
    
management:  endpoints:    web:      exposure:        include:        - "*"
  endpoint:    health:      enabled: true